/** */
export const BOOKING_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const BOOKING_STATUS_VALUES = Object.values(BOOKING_STATUSES);

/** */
export const BOOKING_LIMITS = {
  MAX_SEATS_PER_BOOKING: 5,
} as const;

export const BOOKING_EXPIRE_MINUTES = {
  DRAFT: 5,
  PENDING_PAYMENT: 10,
} as const;

/** */
export const BOOKING_SEAT_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  SOLD: 'SOLD',
} as const;

export const BOOKING_SEAT_STATUS_VALUES = Object.values(BOOKING_SEAT_STATUSES);
